### ISSUE TITLE
Keplr doesn't always work if permissions are changed to "On Click"

### ISSUE THREAD

**Issue by ebuchman** [chainapsis/keplr-wallet#101]
Keplr requires pretty strong permissions: `Allow this extension to read and change all your data on websites you visit`.

Chrome let's you reduce scope on this from `On all sites` to only `On click`. However if I change this permission to `On click` then Keplr gets a bit flaky. Specifically on the hub I started getting this error `Fail to send token: Network Error`, even though Keplr was still working fine on my test chain. 

If I change the permission back to `On all sites` then Keplr works again.

**Comment by gootecks** [comment]
So glad that you pointed this out!  I fumbled through the setup of Keplr to try out Secret and had it set to "on click."  

After thinking that I'd lost some bridged tokens due to not having any SCRT, I was relieved to find that my tokens were bridged, but I couldn't view them at all.  So then I realized I needed to add the tokens, but couldn't figure out why I was getting a network error every time!  

This solved it though.  I have no idea why the permissions are so finicky, but IMO there should be something somewhere that says if you're getting network errors, to check this setting.  I realize crypto and defi are still in its early phases, but I think many normies would have given up at this stage, if not sooner.
