### ISSUE TITLE
Delegate to validators that are not in the active set

### ISSUE THREAD

**Issue by cmwaters** [chainapsis/keplr-wallet#216]
This is more a feature request aimed at the browser client rather than the extension but I wasn't sure where else to write it up. I'd also consider this a nice to have and I know this team is quite busy so I'm fine if this gets backlogged.

Essentially, Keplr doesn't allow you to perform any staking actions to validators outside of the active set. You can't claim rewards, redelegate or simply delegate. It would be nice if Keplr also allowed these actions for all validators, not just those in the active set.

**Comment by dogemos** [comment]
This was more of an intentional design decision back when we launched Keplr last year to prevent users from delegating and realizing that inactive validators do not have staking rewards.

As a good solution, I think we can split the staking interface into different tabs add a small info section on the 'inactive' validators letting users know about this.

**Comment by cmwaters** [comment]
Yeah that makes sense 👍
