### ISSUE TITLE
New Chain Dropdown design

### ISSUE THREAD

**Issue by chmichael** [chainapsis/keplr-wallet#228]
Hello,
  1) I propose to use a similar "Chain" dropdown as mintscan but a bit more compact!
  2) add a search field like osmosis. 
  3) Use of stylish scrollbars. (Look https://github.com/osmosis-labs/osmosis-frontend/issues/113)

Also a dropdown or a button that will show the MapOfZones it will be cool!

The custom added chains (not the official ones) will not have any icon so an API call to the extension might provide them this functionality/icon.

Thank you

![keprl](https://user-images.githubusercontent.com/13120950/146698728-93ba8ec3-f5f7-4cdd-b92c-b7f61ca67180.jpg)
u

**Comment by intercos** [comment]
Another suggestion : Chain Dropdown design
A "Down-down menu with search function" would be better.
Because if there are thousands of IBC connections in the future, it will be difficult to find chain items.

![sdd1](https://user-images.githubusercontent.com/94884108/146806695-fa3a9022-f742-43aa-ada8-334de6bc5a10.jpg)
