### ISSUE TITLE
SecretNetwork: Getting "account sequence mismatch, expected 555, got 554: incorrect account sequence" after transaction

### ISSUE THREAD

**Issue by floAr** [chainapsis/keplr-wallet#230]
**Describe the bug**
I can do a transaction with keplr and it has a nonce of 553. Tx is successfull. I do another transaction right after that and sign a tx with nonce 554. Keplr fails the transaction and produces above error.

**To Reproduce**
1. Go to https://mysticskulls.com/
2. Click on have an nft attuned
3. Reveal any trait -> success
4. Reveal another trait -> error

**Expected behavior**
Keplr wallet should increment the expected nonce by 1 for each transaction

**Device details (please complete the following information):**
 - OS: Windows
 - Browser: Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
 - Keplr Version: 0.9.9
 - Hardware Wallet:  Ledger Nano S Firmware version 2.0.0 + Cosmos Ledger App 2.18.0

**Comment by floAr** [comment]
Adding to this. It seems like this only occurs using a hardware wallet (At least I have only been able to reproduce using hardware wallets) It happens to almost all site (Keplr extension itself included: Cant swap, or claim unless I clear cache and restart the browser)

**Comment by dogemos** [comment]
Hi @floAr,

Keplr doesn't store the current account sequence locally.

For web apps connected to Keplr such as [mysticskulls.com](mysticskulls.com), the webapp will be telling the sequence number for Keplr to sign.

If there is a sequence mismatch error, it could be likely that the node that [mysticskulls.com](mysticskulls.com) is connected to is falling out of sync, rather than an issue from the Keplr side.

**Comment by floAr** [comment]
Hey @dogemos just noticed this was closed. The issue also happens when sending tokens directly through Keplr. Could you give some more insights on where Keplr is grabbing the sequence from itself?
