### ISSUE TITLE
Missing e-Money support for several stablecoins

### ISSUE THREAD

**Issue by JDinesenEmoney** [chainapsis/keplr-wallet#238]
The suite of e-Money tokens are only partially supported by default.

Of the six tokens in the e-Money ecosystem, only NGM and EEUR seem to behave as expected.

ESEK, ENOK, EDKK and ECHF all have errors when signing with keplr. It appears that the "chain-To-View-Conversion-Factor" is off. Trying to send 1 ESEK, keplr asks the user to sign off on 1.000.000 ESEK being transferred.

Also, the four stablecoin balances (ESEK, ENOK, EDKK and ECHF) are not displayed in the keplr wallet, even though the address clearly holds funds (see https://www.mintscan.io/emoney/account/emoney1dhdlcrqdk0ze9n22my5e0ttyayc2zxgv42vmzq)

Thanks in advance and please let me know if more info is needed.

**Comment by dogemos** [comment]
Hi there @JDinesenEmoney,

We've looked into this and it seems like this is because ESEK, ENOK, eDKK, and ECHF are not in the active token lists. In this case, Keplr displays the raw data. What added to the confusion was the fact that the on-chain denom of ESEK is not `uesek`, but `esek`– so transferring '1 ESEK' in the raw data shown in Keplr is shown as `1000000esek`.

Do you think you could submit a PR similar to [this](https://github.com/chainapsis/keplr-wallet/pull/210) updating the currency?

I believe that should resolve the issue and will be released through the next version update.
