### ISSUE TITLE
diffirent address when import private key from metamaks

### ISSUE THREAD

**Issue by hanhbd1** [chainapsis/keplr-wallet#257]
I export my private key from metamask then import back to keplr.
But it seem the address of both wallet is not the same. 

How can I do in that case.

Thanks you.

**Comment by TheMarstonConnell** [comment]
Metamask is entirely different and not built for the cosmos network. Therefore they are inoperable.

**Comment by hanhbd1** [comment]
@TheMarstonConnell : thanks for answer. But I have a little issuse that when I connect with the my private chain build on evmos. the wallet in metamask has balance but the keplr is not. 
note that the private key is export from key-ring of evmosd.

**Comment by fomolabsdev** [comment]
> Metamask is entirely different and not built for the cosmos network. Therefore they are inoperable.

Despite that's absolutely true, I understand people could get confused and, since many people who just come to Cosmos ecosystem are used to Metamask, a bit of information about do's and dont's would be helpful.

An example: Keplr and Cosmos works with Bech32 format address while Metamask uses EIP-55 format. Both are interchangeable. Given a network, one can convert a Bech32 address to a EIP-55 address.

Ie: https://lone.fi/bech32toeip55 (disclaimer: this is mine)

I'm just starting with Keplr and Cosmos (chain built on Evmos), and I have the same question as the OP:

Given a private key for a wallet in EVM, is it possible to use that private key to import *the same wallet* in Keplr? If it's not possible, any misunderstanding here could drive to lose funds. Think of this scenario:

I create a random EVM wallet with private key PK and EIP-55 addresss 0x1234. I convert that address 0x1234 to Bech32. That's genesis1zg6qhhz06d in Genesis L1 network. If I import the private key PK in Keplr, the address is different from genesis1zg6qhhz06d. So if I ask anyone to send me tokens to genesis1zg6qhhz06d...

Well, my mistake 😓. I'm realizing funds won't lose because wallet can be controled from EVM side. But question is still legit: is is possible to import in Keplr a wallet given it's private key from Metamask?

**Comment by giansalex** [comment]
@fomolabsdev  It seems that it is necessary to add an additional option (`algo`) to the wallet config, and implement the algorithm used in evmos (`eth_secp256k1`)
