### ISSUE TITLE
Support sign-direct for IBC transfer

### ISSUE THREAD

**Issue by tianrandailove** [chainapsis/keplr-wallet#352]
some chain that by cosmos SDK only support sign-direct tx, but keplr-wallet only support sign-amino tx

keplr-wallet both support  sign-direct tx and sign-amino tx , so that developer can choose sign way by config

**Comment by Thunnini** [comment]
what are you referring to by “some chains”?

**Comment by xiangjianmeng** [comment]
> what are you referring to by “some chains”?

OKC，transplant IBC to OKC which only support Direct Signature.

**Comment by tianrandailove** [comment]
@Thunnini 
OKC, OKC was originally called okexchain, it only supports direct signature

**Comment by Thunnini** [comment]
OKC is not an officially supported chain, and Keplr does not have any responsibilities to maintain it. 
Apart from that, sign direct cannot support ledger cosmos app. Since Keplr has to support ledger, we do not send transactions with sign direct. If a transaction only supports sign direct, ledger usage would not be supported, but it would have to be solved within the chain itself. Also, the ibc transfer ui that Keplr supports is for development purposes, so if there’s limitations or restrictions to use that functionality, you might as well want to use the cli or make your own web interface. If it’s implemented within a webpage, ibc transfer would be able to sent via sign direct

**Comment by Thunnini** [comment]
I was trying to say that ibc transfer only supporting DirectSignature is not an issue of Keplr, but should be addressed as the issue of OKC chain. Keplr only officially supports cosmos-sdk's general modules. If those has been modified, there's possibility that they might not be compatible and Keplr does not support the individual integrations and modifications. There's no way to send signDirect via ibc transfer in Keplr. signDirect is not supported within Ledger as well. With that being said, Keplr UI does not have plans to use signDirect.

**Comment by xiangjianmeng** [comment]
thanks for your reply, will it be practicable that we modify keplr wallet codes to support Direct sign for IBC transfer?

**Comment by Thunnini** [comment]
This is an open source project, you can modify it as much as you want in your own fork: it’s just that such PR would not be merged to main. I think the easiest way to solve this would be to support animo in the chain side. There’s a lot of cases where different chains update so that they support Amino, without initially knowing that DirectSignature is not supported in ledger

**Comment by xiangjianmeng** [comment]
I see, appreciate.
