### ISSUE TITLE
Support React Library

### ISSUE THREAD

**Issue by siulee2** [chainapsis/keplr-wallet#465]
Hi.

I thought that It would be beeter if this code is supported as common react library.
Because someone can't figure out this is stable open source library or keplr mobile specific one.

**Comment by Thunnini** [comment]
There is a description about this in README.md

### Disclaimer
Usage of any other packages besides @keplr-wallet/types is not recommended.
 - Any other packages besides @keplr-wallet/types are actively being developed, backward compatibility is not in the scope of support.
 - Since there are active changes being made, documentation is not being updated to the most recent version of the package as of right now. Documentations would be updated as packages get stable.
