### ISSUE TITLE
Plans for supporting ADR-36

### ISSUE THREAD

**Issue by wgwz** [chainapsis/keplr-wallet#474]
I would like to inquire about the plans for supporting ADR-36. Within [the Keplr docs](https://docs.keplr.app/api/#request-signature-for-arbitrary-message) it is stated:

> This is an experimental implementation of [ADR-36 (opens new window)](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-036-arbitrary-signature.md). Use this feature at your own risk.

Does this mean that you are working to make this a stable API? Or is there a significant risk that this will be removed or changed in a future version?

**Comment by Thunnini** [comment]
The current problem with ADR-036 is that there is no real on-chain implementation. There is no spec that actually works, and the ADR-036 documentation doesn't cover everything we need to get it working. The blanks required for implementation were made at keplr's own discretion. Although this feature was pre-made due to high requests, there is no guarantee that the future will be perfectly the same as it is now. But what is clear is that the functionality won't go away.

**Comment by cyborgshead** [comment]
@Thunnini we are successfully using ADR-36 in our Moon Code signing process with cosmos' ecosystem addresses with Keplr as the signer, more than 8k signs to date
https://github.com/cybercongress/cw-cybergift/blob/main/contracts/cw-cyber-passport/src/helpers.rs#L140
