### ISSUE TITLE
Evmos doesn't appear in assets listings on a Ledger wallet

### ISSUE THREAD

**Issue by freak12techno** [chainapsis/keplr-wallet#480]
**Describe the bug**
I have two wallets, one imported from mnemonic, other from Ledger. On the first one, I can see Evmos in my assets:
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/83376337/182665590-7e3fd70b-7731-401a-9dbf-9ef951ed66a9.png">
While on the Ledger wallet I cannot see it, although I have some Evmos staked and on balance:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/83376337/182665797-cfced214-7382-431f-bded-a59d2af917e4.png">

Moreover, when going into chain listings, it has I have zero assets, which is not true:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/83376337/182665939-010d1d61-4034-477a-9572-90a64992c2be.png">

**To Reproduce**
1. Have Ledger wallet imported into Keplr

**Expected behavior**
1. Dashboard should display my assets correctly
2. Evmos chain page should display my assets correctly

**Screenshots**
See above

**Device details (please complete the following information):**
 - OS: Mac OS 
 - Browser: Chrome
 - Keplr Version: 0.10.14
 - Hardware Wallet: Ledger Nano S

**Additional context**
None

**Comment by serkor1** [comment]
This is a general problem also reported on Reddit. It appears that Keplr with Ledger, doesn't support EVMOS. Is there a timeline on when you expect to create this compatibility?

**Comment by delivan** [comment]
@freak12techno @serkor1 Thanks for the report!

Keplr only supports Ledger Cosmos App and will continue to do for a long time. Evmos does not yet support the Cosmos App. So first, Evmos needs to support the Ledger Cosmos App. I heard they have a plan to support it within a few weeks. If Evmos supports the Ledger Cosmos App, Keplr can support Evmos, but I'm not sure because the address architecture is fundamentally different.
