### ISSUE TITLE
How to monitor user switching network？

### ISSUE THREAD

**Issue by CoderKwong** [chainapsis/keplr-wallet#502]
Hello!
How web pages monitor users to switch networks？The document only has `keplr_keystorechange` monitor user change account.

**Comment by Thunnini** [comment]
#399 

Personally, I think this feature is a bad design done in metamask. When using metamask, sometimes the web page asks the user to set a different chain in the metamask because it depends on the currently selected chain setting of the metamask. And at the same time, another web page would ask to change the chain setting again and puts the user in this infiniite loop...

Keplr was designed as a multi-chain from the beginning, and it was designed so that the web page and the chain selected in Keplr were separated. Therefore, I think that it is better to let the user choose the chain to use in the web page independently, without the web page depending on the chain setting selected in Keplr.

However, since there have been many requests for these features, I am willing to consider more deeply about this feature.
