### ISSUE TITLE
Add Keystone hardware wallet into Keplr

### ISSUE THREAD

**Issue by aaronisme** [chainapsis/keplr-wallet#537]
Hi, This is Aaron from the Keystone team. We would like to introduce the Keystone hardware wallet into the Keplr wallet. 

We would like to contribute the code on Keplr side for the integration, we have checked the code these days. Here is the general technical idea and implementation plan for the integration. 

## Connecting

The Keystone device will export the public key via QR Codes and Keplr can scan the QR Code to retrieve these data. the data will be saved in the MultiKeyStore in the Keyring.

## Transaction Signing 

When the user signs the transaction, the transaction data will be encoded in the QR Codes, and the keystone device scans the QR Codes, and returns the signature after signing.  The Keplr wallet will retrieve the QR codes' signatures, construct the transaction, and broadcast it into the blockchain. 

## Introduced Change

Currently, Keplr wallet has already supported the ledger which gives us a good reference for the implementation. And we will follow the current code pattern when introducing the Keystone wallet. Here is a general list of what we will change based on our current investigation. 

1. Add a keystone service in the background keyring like: `packages/background/src/keystone` just like the ledger service This service includes “getPublicKey”, “sign”, and “useKeystone” these functions.

2. New message type for Keystone for background and UI communication.

3. Some UI changes will be introduced since we are using the QR Code for the data transmission.

**Comment by Thunnini** [comment]
I'll give you advice on the following.

 - Keplr has other approach to make sure to connect the ledger. On metamask, it doesn't handle the case of connection failure with ledger. Thus, it always fails to interact with ledger if ledger is not initialized on metamask's expanded view mode first. To solve this problem, Keplr try to open new popup window to connect ledger with UI when background process fails to connect ledger.
 - The role of `interactionService.waitApprove` is to open new popup UI and wait for user's interaction (approve or reject). In the ledger module, this is used when ledger connection is failed. When popup UI opens, user can try to connect on popup UI and if connection succeeds, the interaction is approved and logic proceeds on background.
 - However, connection with keystone never fails because keystone uses QR, I think there is no need to follow this way.
 - I recommend to open the new popup UI to display keystone QR by using `interactionService.waitApprove`. And, on UI, when user succeeds interaction with Keystone, you can return the address or signature to background process by using interaction store and allow them to proceed the logic.

**Comment by renfengshi** [comment]
@Thunnini Thanks for your advice.

I'm a member of Keystone team, who is responsible for the development of the integration.

I have received your advice, and I am also developing according to this idea.
