### ISSUE TITLE
Logging in similar to metamask

### ISSUE THREAD

**Issue by MarkH1994** [chainapsis/keplr-wallet#567]
Hi guys,

It would be very nice if we can create user accounts (for added functionality), where the user logs in using Keplr, and we can indeed verify whether they are logged in, without sending false requests to the backend. In MetaMask, we found a way to do it with the following [tutorial](https://www.toptal.com/ethereum/one-click-login-flows-a-metamask-tutorial). Is there also a possibility that this will be added with Keplr? And can it be done using PHP?

Looking forwards to your replies. Thanks!

**Comment by Thunnini** [comment]
https://docs.keplr.app/api/#request-signature-for-arbitrary-message
Using `singArbitrary` stated in the link above, you'd be able do something similar with what you have asekd. 

https://github.com/chainapsis/keplr-wallet/blob/master/packages/cosmos/src/adr-36/amino.ts#L119
The verification should be done in the backend, but unfortunately we don't have the code for php, please use the link above to make your own implementation. 

To prevent replay attack in the data that is to be signed, please use the field like sequence in the tx. If the chain needs to be specified as well, use chain id as well. Also, make sure to include explanation for what the user is signing for. 

I'm not quite sure what you mean by "false request", but I do think that it is impossible to stop a request from the internet. Backend should be in charge of verifying for all cases. Make sure you utilize the data field at its most so that the user understands what they are signing for.
