### ISSUE TITLE
Support for walletconnect V2

### ISSUE THREAD

**Issue by ap-justin** [chainapsis/keplr-wallet#575]
Wallet connect v1 will be [depracated next year](https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

would be really nice for keplr to support these [new methods](https://docs.walletconnect.com/2.0/advanced/rpc-reference/cosmos-rpc) and provide another example like this [helpful v1 example](https://github.com/chainapsis/keplr-wallet/tree/master/packages/wc-client-example)

**Comment by HeesungB** [comment]
Thank you for your interest.

We are preparing for v2 migration.

**Comment by dhinterlechner** [comment]
any update on this? as the keplr link to mobile is not working anymore...

**Comment by HeesungB** [comment]
@dhinterlechner We update to Wallet Connect 2.0.
Could you tell me where it doesn't work?

**Comment by dhinterlechner** [comment]
Keplr extension: 0.12.17 and Keplr Mobile (Android): 1.1.16
expected behaviour: you can link your wallets form the desktop extension to your mobile app.

Steps:
- Desktop: go Settings, General, Link Keplr Mobile, input your PWD -> you get a QR code
- Mobile: open keplr, go to import wallet, link with keplr, scan QR code. - no result

Possible root cause:
the QR code of the browser extension points to a domain bridge.walletconnect.org - this subdomain does not exists any more...

**Comment by HeesungB** [comment]
@HeesungB It will update maybe next version!

https://github.com/chainapsis/keplr-wallet/pull/803/files
