### ISSUE TITLE
Keplr 2.0 scrolling disabled

### ISSUE THREAD

**Issue by janfabian** [chainapsis/keplr-wallet#743]
**Describe the bug**
After upgrade to Keplr 2.0 I'm unable to scroll. Extension can be opened, but to navigate to bottom part I need to move only using using keyboard and cursor (attached screencast)

**To Reproduce**
1. open Keplr
2. no scrollbar, mouse scroll not working as well

**Expected behavior**
Scrolling enabled.

**Screenshots**
[Screencast from 2023-06-05 11-40-05.webm](https://github.com/chainapsis/keplr-wallet/assets/98740/f20edc6a-a210-47ff-a68f-bbee223d8132)

**Device details (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser: Brave Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)
 - Keplr Version: 0.12.5

**Comment by Thunnini** [comment]
There have been some users reporting this issue. Unfortunately, our team has been unable to reproduce this issue. It seems that some of the linux users are experiencing this problem. I can't give you an exact solution because I couldn't reproduce the issue... In v0.12.9, the scroll-related layout was improved. Please check if v0.12.9 fixes this issue.

**Comment by janfabian** [comment]
@Thunnini it is fixed for me with the latest update. Great thanks 👍
