### ISSUE TITLE
static coin type in importing ledger wallet

### ISSUE THREAD

**Issue by leejw51crypto** [chainapsis/keplr-wallet#95]
for CRO, coin type is 394, 
currently, when importing from ledger, coin type is fixed with 118
generated cro address is different from chain-desktop-wallet.

can `coin type` be editable ?

**Comment by arno01** [comment]
I've noticed the same when realized the Crypto.org address in Keplr is different from the [Crypto.org Chain Desktop Wallet](https://github.com/crypto-com/chain-desktop-wallet/releases) when both imported from my Ledger Nano X.

Looking at the ledger crypto.org app, they are using this derivation path:

```
m / purpose' / coin_type' / account' / change / address_index
m/44'/394'/0'/0/0 
```

https://github.com/crypto-com/ledger-crypto/blob/cro/app/src/coin.h#L30-L34

```
#define HDPATH_0_DEFAULT     (0x80000000u | 0x2cu)
#define HDPATH_1_DEFAULT     (0x80000000u | 0x18au)
#define HDPATH_2_DEFAULT     (0x80000000u | 0u)
#define HDPATH_3_DEFAULT     (0u)
#define HDPATH_4_DEFAULT     (0u)
```

```
HEX to DEC:
0x2c = 44
0x18a = 394  <-- coinType
```

This derivation path is also mentioned in the official docs https://crypto.org/docs/wallets/mainnet-address-generation.html

I think the same should be valid for Keplr.

Refs:
- https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

**Comment by arno01** [comment]
Not sure whether this is related, but there seem to be a typo in the code => `seletables` instead of `selectables`
https://github.com/chainapsis/keplr-extension/blob/2119bdb1802e6f2f0c3f19071c9818a84416b20d/packages/stores/src/core/keyring.ts#L106

**Comment by arno01** [comment]
Ok, I think I've figured this out now.

The reason Keplr-extension is using **coinType** `118` (ATOM) is because it relies on [Ledger's Cosmos app](https://github.com/LedgerHQ/app-cosmos) which has **coinType** hardcoded to `118` (as expected, since ATOM is Cosmos's default token)  => https://github.com/LedgerHQ/app-cosmos/blob/aa6d78c512fec10651c99195185766bc01ffa4a8/app/Makefile#L33

The devs have also mentioned this in the keplr's code => https://github.com/chainapsis/keplr-extension/blob/8201fc3c832331f36909880af08d83bfafe1aa1f/packages/background/src/ledger/service.ts#L29-L32

So, there is that.

:warning: This also makes Keplr-extension generate **all** Cosmos-based addresses using only **coinType: 118** (when the key gets derived with Ledger only due to Ledger's Cosmos-app using **coinType: 118** as just explained above), very much likely breaking the compatibility with any other dedicated wallets such as Cosmostation. (i.e. people using Keplr-extension with Ledger will be getting different addresses for non-ATOM tokens.)

----
## Hack: force keplr to get 394 CRO address

> :warning: Do not rely on any other wallet generated with this modification except for the Crypto.org wallet! You can use this method to move your funds off to a different address. Make sure to remove the modified Keplr-extension after you are done!

Now, if you _really really_ want to get the same CRO address in the Keplr-extension as you are seeing in your [Crypto.org Chain Desktop Wallet](https://github.com/crypto-com/chain-desktop-wallet/releases).

The [Crypto.org Chain Desktop Wallet](https://github.com/crypto-com/chain-desktop-wallet/releases) uses [Ledger's Crypto.com App](https://github.com/LedgerHQ/app-cryptocom) which [does use](https://github.com/LedgerHQ/app-cryptocom/blob/5cda94bdc919622b12e418cfccc96237dce02257/app/Makefile#L34) the correct **coinType** => `394` (CRO).


- Modify `118` to `394` in [service.ts](https://github.com/chainapsis/keplr-extension/blob/8201fc3c832331f36909880af08d83bfafe1aa1f/packages/background/src/ledger/service.ts#L32) file of keplr-extension;
- Build it and open it with Google Chrome
- Open "Crypto.org" app in your Ledger
- Use your new Keplr-extension to import the keys.

**Comment by slimslyde** [comment]
This is especially frustrating, as implementations of Iris also seem to have to deviate from the standard. I have encountered this with Uptick project's NFT app: When importing a BIP-44 mnemonic, it forces you to use the coin_type 112 (atom) and not 566 (iris). Somebody sent me an Uptick NFT to my 556 wallet , but I have no way of interacting with it, as I need to import my 556 iris wallet to Uptick, but they only allow for 112.

**Comment by slimslyde** [comment]
I noticed now that when I re-import my wallet into Keplr, it asks me which derivation I want to use as my Iris wallet (112 or 566). This is better, however, it shouldn't even ask about 112 (surely??) as this can cause confusion depending on how other projects implement seed importing.

**Comment by DarkGhost7** [comment]
Hello devs why can't I add tokens form terra derivation 330?

**Comment by dogemos** [comment]
Hi @arno01,

We are currently not planning on adding support for other Ledger apps. I've summarized some of the nuances and thoughts on this matter on this blogpost.

We're working with multiple stakeholders (including Ledger) for a more long-term and sustainable path to interchain address derivation and standardization. This will involve the finalization of sign mode textual, and hopefully a 'interchain'-focused Ledger app that supports the feature.
